[package]
name = "LR35902"
version = "0.1.0"
authors = ["Stefan Mitic <atimilam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
